name: stocker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # 아이폰 스타일 기본 아이콘 (Cupertino 디자인용)
  cupertino_icons: ^1.0.8

  # 화면 크기/비율 자동 조절 (반응형 대응)
  flutter_screenutil: ^5.9.3

  # 로컬 푸시 알림 (출석 알림 등)
  # flutter_local_notifications: ^19.3.0

  # 네트워크 및 인증
  dio: ^5.8.0+1                    # REST API 통신
  flutter_secure_storage: ^9.2.4   # JWT 등 민감정보 보안 저장
  shared_preferences: ^2.5.3       # 유저 설정값 등 간단 캐시 저장

  # 상태 관리
  provider: ^6.1.5                 # 전역 상태 관리
  haptic_feedback: ^0.5.1+1         # 햅틱 피드백
  go_router: ^16.0.0

  # 챕터, 퀴즈, 출석 관련 UI
  percent_indicator: ^4.2.5        # 진척률 게이지 표시
  table_calendar: ^3.1.3           # 출석용 달력 (intl 충돌 방지용 버전)
  flutter_toggle_tab: ^1.5.1       # OX 퀴즈 선택형 탭 UI

  # 통계 시각화
  fl_chart: ^1.0.0                 # 꺾은선, 막대 등 통계 그래프

  # 유틸리티 및 환경 설정
  flutter_spinkit: ^5.2.1          # 로딩 인디케이터
  flutter_dotenv: ^5.2.1           # .env 환경 변수 관리

  # 메모 기능 (리치 텍스트 에디터)
  flutter_quill: ^11.4.1           # 메모 입력, 체크리스트 등 지원

  # 앱 통합 관리
  flutter_launcher_icons: ^0.14.4  # 앱 아이콘 관리 flutter pub run flutter_launcher_icons:main 
  change_app_package_name: ^1.5.0  # 앱 이름 관리  flutter pub run change_app_package_name:main com.팀명.stocker


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# flutter_launcher_icons
# flutter_launcher_icons:
#   image_path: "assets/icon/app_icon.png"
#   android: true
#   ios: true

flutter:
  uses-material-design: true
